[project]
name = "my-first-mcp-server"
version = "0.1.0"
description = "This is to create an MCP server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.14.1",
    "pandas>=2.3.2",
]
